version: "3.9"
services:
  grafana.service:
    container_name: grafana
    image: "grafana/grafana:latest"
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true

  tempo.service:
    container_name: tempo
    image: "grafana/tempo:latest"
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - ./tempo/tempo-data:/tmp/tempo
    ports:
      - "14268:14268" # jaeger ingest
      - "3200:3200"   # tempo
      - "4317:4317"   # otlp grpc
      - "4318:4318"   # otlp http
      - "9411:9411"   # zipkin

  loki.service:
    container_name: loki
    image: "grafana/loki:latest"
    command: [ "--config.file=/etc/loki.yaml" ]
    volumes:
      - ./loki/loki.yaml:/etc/loki.yaml
    ports:
      - "3100:3100"

  promtail.service:
    container_name: promtail
    image: "grafana/promtail:latest"
    command: [ "--config.file=/etc/promtail.yaml" ]
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail/promtail.yaml:/etc/promtail.yaml

  prometheus.service:
    container_name: prometheus
    image: "prom/prometheus:latest"
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  synthetic-load-generator:
    container_name: load_gen
    image: omnition/synthetic-load-generator:1.0.25
    volumes:
      - ./load-generator/load-generator.json:/etc/load-generator.json
    environment:
      - TOPOLOGY_FILE=/etc/load-generator.json
      - JAEGER_COLLECTOR_URL=http://tempo.service:14268
    depends_on:
      - tempo.service
