global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo.service:3200' ]
  - job_name: 'go-metrics-example'
    static_configs:
      - targets: [ 'go.metrics.service:2112' ]
