apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  uid: prometheus
  orgId: 1
  url: http://prometheus.service:9090
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
- name: Tempo
  type: tempo
  access: proxy
  uid: tempo
  orgId: 1
  url: http://tempo.service:3200
  basicAuth: false
  isDefault: true
  version: 1
  editable: false
  apiVersion: 1
  jsonData:
    nodeGraph:
      enabled: true
    lokiSearch:
      datasourceUid: loki
- name: Loki
  type: loki
  access: proxy
  uid: loki
  orgId: 1
  url: http://loki.service:3100
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
  jsonData:
    derivedFields:
      - datasourceUid: tempo
        matcherRegex: "traceId (\\w+)"
        name: traceID
        url: '$${__value.raw}'
